# Team Challenge · Sprint 03-04 - Catálogo de películas

**Dataset:**  
- [movies.csv](./data/movies.csv)
- [ratings.csv](./data/ratings.csv)
- [tags.csv](./data/tags.csv)
- [links.csv](./data/links.csv) 

**Entregables:** Repositorio de GitHub con el código fuente. Puede ser scripts de python o notebook ordenado, código reproducible, README con cómo ejecutar el proyecto.

**Control de versiones:** gestión del proyecto con **GitHub desde el primer día**. Trabajar en equipo en paralelo con **ramas**, **pull requests** y revisión entre compañeros.

**Parte 1 (Pandas):** Data analytics (Pandas)

**Parte 2 (TMDB):** una petición `GET /3/movie/{id}` por película; definid `TMDB_API_KEY` o `TMDB_READ_ACCESS_TOKEN` en el entorno (sin subir claves al repo).

**Parte 3 (Gemini):** añadir `overview_es` a `movies10` a partir de los `overview` de TMDB; definid `GEMINI_API_KEY` o usad `getpass` (sin subir claves al repo). Requiere `pip install google-genai`.

**Parte 4 (opcional):**
- **A)** catálogo ampliado (`pitch_es`, `edad_sugerida`, `temas`).
- **B)** recomendador por género.

## Trabajo en equipo y control de versiones

- Crear el **repositorio en GitHub** al inicio (día 1–2), no al final.
- Definir una rama principal (`main`) y una para desarrollo (`develop`) y ramas por tarea (p. ej. `feature/parte1-pandas`, `feature/tmdb`, `feature/gemini`).
- Integrar el trabajo con **pull requests** hacia `develop`; al menos **una PR revisada y mergeada por miembro** del equipo.
- Evitar trabajar en en `main` es la rama de "producción"
- Resolver conflictos en ramas antes del merge.
- **README:** cómo clonar el repo, instalar dependencias, configurar claves (`TMDB_*`, `GEMINI_API_KEY`) y ejecutar el notebook o scripts.
- **No subir claves** al repositorio (usar `.gitignore` para `.env` si aplica).

## Parte 1: Data analytics (Pandas)

### 1. Ingesta de datos

- Los CSV están en **`Team_Challenges/TC_01_Sprint_03_04/data/`**.
- Cargar con **Pandas** los cuatro ficheros: `movies.csv`, `ratings.csv`, `tags.csv`, `links.csv`.
- Comprobar para cada `DataFrame`: `shape`, columnas, `dtypes`, `head` y conteo de nulos.

In [ ]:
# --- Apartado 1: Ingesta de datos ---

### 2. Columna `year` desde el título

- En el dataset de películas. el año de estreno suele aparecer **entre paréntesis al final** de `title`, p. ej. `Batman (1989)`.
- Implementad una función (`year_from_title`) que devuelva un entero de cuatro cifras o valor ausente (`NaN` / `<NA>`) si el título no sigue ese patrón.
- Añadid la columna **`year`** a `movies` como numérico (`pd.to_numeric(..., errors="coerce")`).
- Editar el campo `title` para que no contenga el año de estreno.
- Contad cuántas películas **no** tienen año reconocible y mostrad **una pequeña muestra** de sus títulos (casos límite).

In [ ]:
# --- Apartado 2: columna `year` ---

### 2. Unificación de datos (*merge* / *join*)

- Entender las **claves** entre tablas (p. ej. `movieId` une `movies`, `ratings`, `tags` y `links`).
- Construir un esquema unificado: al menos una tabla **película–usuario–rating** (ratings enriquecida con título y géneros) y otra con **película–tags** si procede.
- Usar `merge` (u operaciones equivalentes) con criterio claro: tipo de unión (*inner* / *left*), duplicados generados y cómo se resuelven.
- Imprimir las 10 primeras filas de las tablas resultantes.
- Dejar documentado qué filas se pierden o se multiplican al unir y **por qué** es aceptable en vuestro caso de uso.

In [ ]:
# --- Apartado 3: Merge / join  ---

### 4. Agregaciones y segmentación

- Usar `groupby` (por usuario, por película o por género) con al menos una agregación multi-columna (`agg`).
- Comparar dos segmentos (p. ej. usuarios con muchas valoraciones vs. pocos; o por **década** usando la columna `year` del apartado 3) con tablas resumen.

In [ ]:
# --- Apartado 4: Agregaciones ---

### 5. Preguntas sobre los datos (`movies`)

**Requisito:** haber creado la columna `year` en el **apartado 2**.

1. **Cuántas** películas están listadas en `movies`.
2. **Cuáles** son las **más antiguas** (menor año extraído del título).
3. **Cuántas** tienen **"Dracula"** en el título (coincidencia parcial, sin distinguir mayúsculas).
4. **Títulos más comunes**.
5. Películas con **"Exorcist"** ordenadas de la más antigua a la más moderna.
6. **Cuántas** con año **1950**.
7. **Cuántas** entre **1950 y 1959** inclusive.
8. **Año** de la película con título exacto **`Batman`** (y contraste con otras *Batman*).
9. Listado de películas que tienen como tag "sci-fi" y "adventure"
10. ¿Cuál es la tag más repetida?

In [ ]:
# --- Apartado 5: Preguntas sobre `movies` ---

## Parte 2: Petición HTTP a la API de TMDB

### Endpoint

`GET https://api.themoviedb.org/3/movie/{tmdb_id}`

Ejemplo público de la misma forma que en la documentación de TMDB: **`https://api.themoviedb.org/3/movie/100`** (el número es el `tmdb_id`; en vuestro caso usaréis el `tmdbId` de cada fila de `links`).

### Tareas

1. Construir un **`DataFrame` `movies10`** con **10 películas** del dataset original (por ejemplo las 10 primeras filas que tengan `tmdbId` tras unir `movies` con `links`).
2. Escribir una función **`fetch_movie_details(tmdb_id)`** que haga la petición anterior y devuelva al menos **`overview`** y **`homepage`** (texto vacío si vienen nulos).
3. Recorrer `movies10` y **añadir** a cada registro esas dos columnas en el propio `DataFrame`.

### Autenticación

Para poder acceder a la API de TMDB, debéis hacer uso del ACCESS TOKEN o de la API KEY que te proporcionan al registrarse. Recomendamos probar los endpoint en POSTMAN para hacer las pruebas de la llamada a la API antes de crear el script en Python. Deberíais tener en vuestro proyecto:**`TMDB_API_KEY`** (query `api_key`) o **`TMDB_READ_ACCESS_TOKEN`** (cabecera `Authorization: Bearer …`). Podéis crear un proyecto con variables de entorno o usar una celda de código usando **`getpass`** (entrada oculta, solo esa sesión del kernel). 

No guardéis claves en el notebook

# Ejercicio 2 — Enriquecimiento de datos con la API de TMDB
### PRESENTACION
## Contexto
Explicación breve del dataset MovieLens y de los archivos usados.

## Objetivo
Unir datos locales con datos externos mediante la API de TMDB.

## Qué vamos a hacer
Lista de pasos del ejercicio.

# Análisis Exploratorio (EDA)

## Carga de datos
Explicación + código

## Exploración inicial
Conclusiones sobre columnas, tipos, valores nulos.

## Unión de datasets
Explicación de por qué usamos movieId.

## Selección de películas con tmdbId
Explicación del filtrado.

# Conexión con la API de TMDB

## Introducción de la API Key
Explicación de seguridad.

## Función fetch_movie_details
Explicación de cómo funciona.

## Aplicación de la función
Explicación del proceso.

## Resultado final
Tabla con overview y homepage.


# Conclusiones

Resumen de lo aprendido:
- unión de datasets
- uso de APIs
- enriquecimiento de datos
- importancia del EDA


# Referencias
MovieLens
TMDB API
Pandas
Requests

In [9]:
## PASO 1 IMPORTAMOS LAS LIBRERIAS 

import pandas as pd
import requests
from IPython.display import display ## Para que sea mas visual

In [10]:
## PASO 2 CARGAMOS LOS CSV --> MOVIES Y LINKS

movies = pd.read_csv("data/movies.csv")
links = pd.read_csv("data/links.csv")

In [11]:
## PASO 3 VERIFICACION DE CONTENIDO (COLUNAS, FILAS) Y TAMBIEN SI NOS DEVUELVE UN NAN

    ## QUE FILAS TENEMOS?
display(movies.head())
display(links.head())

    ## VER ESTRUCTURA
movies.info()
links.info()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 228.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

Ambos datasets tienen la columna movieId → clave para unir.

links.csv contiene tmdbId, necesario para llamar a la API.

Hay películas sin tmdbId → deben filtrarse.

In [12]:
## PASO 4 UNIR LOS DATASETS (MOVIES.CSV Y LINKS.CSV)

df = movies.merge(links, on="movieId")
display(df.head())

,movieId,title,genres,imdbId,tmdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357.0
4,5,Father of the Bride Part II (1995),Comedy,113041,11862.0

*Conclusión:*
Ahora tenemos un DataFrame con:

Título

Géneros

imdbId

tmdbId

In [24]:
fetch_movie_details(862)

Error 401 en película 862

('', '')

In [13]:
## PASO 5 SELECCIONAR LAS 10 PRIMERAS PELICULAS
movies10 = df[df["tmdbId"].notnull()].head(10)
display(movies10[["movieId", "title", "tmdbId"]])

   movieId                               title   tmdbId
0        1                    Toy Story (1995)    862.0
1        2                      Jumanji (1995)   8844.0
2        3             Grumpier Old Men (1995)  15602.0
3        4            Waiting to Exhale (1995)  31357.0
4        5  Father of the Bride Part II (1995)  11862.0
5        6                         Heat (1995)    949.0
6        7                      Sabrina (1995)  11860.0
7        8                 Tom and Huck (1995)  45325.0
8        9                 Sudden Death (1995)   9091.0
9       10                    GoldenEye (1995)    710.0

In [ ]:
## PASO 6 INTRODUCIR LA API KEY

from config import API_KEY

In [45]:
import requests
from config import API_KEY

def fetch_movie_details(tmdb_id):
    url = f"https://api.themoviedb.org/3/movie/{tmdb_id}?api_key={API_KEY}"
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        overview = data.get("overview", "")
        homepage = data.get("homepage", "")
        return overview, homepage
    else:
        print(f"Error {response.status_code} en película {tmdb_id}")
        return "", ""

In [46]:
## PASO 8 APLICAMOS EL "OVERVIEW" Y "HOMEPAGE" A LAS 10 PELICULAS
movies10["overview"], movies10["homepage"] = zip(
    *movies10["tmdbId"].apply(fetch_movie_details)
)

In [47]:
## PASO 9 RESULTADO FINAL

display(movies10[["title", "tmdbId", "overview", "homepage"]].style.hide(axis="index"))

# MEMORIA TÉCNICA — Ejercicio 2  
## Enriquecimiento de datos de películas mediante la API de TMDB

---

## 1. Introducción

En este ejercicio se trabaja con el dataset MovieLens, que contiene información básica sobre miles de películas. El objetivo principal es enriquecer estos datos locales utilizando información externa obtenida a través de la API de The Movie Database (TMDB).

Se usan dos archivos CSV:

- `movies.csv`: títulos y géneros.  
- `links.csv`: identificadores externos (`imdbId`, `tmdbId`).  

El identificador `tmdbId` permite acceder a la API de TMDB para obtener, entre otros campos:

- `overview` (sinopsis)  
- `homepage` (página oficial)

---

## 2. Objetivos

- Realizar un análisis de los datos.  
- Identificar la clave común para unir los datasets.  
- Seleccionar un subconjunto de películas con `tmdbId` válido.  
- Conectarse a la API de TMDB de forma segura.  
- Obtener información externa y añadirla al DataFrame.  
- Presentar los resultados de forma clara y estructurada.

---

## 3. Metodología

### 3.1 Carga de datos

Se cargan los archivos CSV con Pandas y se inspeccionan sus primeras filas y estructura (`head()`, `info()`) para comprender el contenido y tipos de datos.

### 3.2 Análisis de los CSV

Se revisan:

- Columnas disponibles en cada CSV.  
- Tipos de datos.  
- Presencia de valores nulos.  

Se identifica que `movieId` está presente en ambos archivos y puede utilizarse como clave para unirlos.

### 3.3 Unión de datasets

Se realiza la unión mediante:

```python
df = movies.merge(links, on="movieId")

## Parte 3: Sinopsis en español con Gemini

Usad el `DataFrame` **`movies10`** de la Parte 2 (columna `overview` en inglés desde TMDB).

### Tareas

1. Configurar **`GEMINI_API_KEY`** (variable de entorno o `getpass`, como en Sprint 4).
2. Crear el cliente **`google-genai`** y una función **`summarize_overview_es(overview, title="")`** que devuelva un **resumen en español de máximo 2 frases**. Si `overview` está vacío, devolver cadena vacía **sin llamar a la API**.
3. Recorrer `movies10` y añadir la columna **`overview_es`**.
4. Mostrar `title`, `overview` (recorte) y `overview_es` para **3 películas**.

### Autenticación

Clave en [Google AI Studio](https://aistudio.google.com/). Variable **`GEMINI_API_KEY`** o celda con **`getpass`**. No guardéis claves en el notebook.

### Prerrequisitos

- Parte 2 ejecutada (`movies10` con columna `overview`).
- `pip install google-genai`

In [ ]:
# --- Parte 3: overview → overview_es con Gemini  ---
# Requiere: `movies10` de la Parte 2. pip install google-genai

## Parte 4 (opcional): extensiones con Gemini

**No obligatorio.** Solo si el grupo terminó las partes 1-3. Podéis elegir **A**, **B** o ambas. Son independientes.

---

### A) Catálogo ampliado en `movies10`

Partiendo de `movies10` (con `overview` y, si ya lo tenéis, `overview_es`), añadid con **una llamada JSON por película**:

- **`pitch_es`**: texto de cartelera en español (máx. 280 caracteres).
- **`edad_sugerida`**: uno de `TP`, `+7`, `+12`, `+16`, `+18`.
- **`temas`**: exactamente 3 temas en español (en el DataFrame, cadena separada por comas).

Función sugerida: **`enrich_catalog_fields(overview, title="", genres="", year=None)`**. Basad la respuesta solo en sinopsis y metadatos; no inventéis reparto ni datos externos. Si `overview` está vacío, no llaméis a la API.

Mostrad 2–3 filas con las columnas nuevas.

---

### B) Recomendador por género

Usad **`ratings_movies`** (Parte 1) y Gemini.

1. **`top_rated_by_genre(ratings_movies, genres, top_n=10, min_ratings=50)`** — filtra por género(s), nota media por `movieId`, devuelve el top N (mínimo `min_ratings` valoraciones por película).
2. **`recommend_movies(candidates, favorite_genres, n=3)`** — el modelo recomienda **solo** del catálogo candidato, con una frase de justificación en español cada una.
3. Probad con 1–2 géneros (p. ej. `["Action", "Sci-Fi"]`): mostrad candidatas y respuesta del modelo.

In [ ]:
# --- Parte 4A (opcional): pitch_es, edad_sugerida, temas ---
# Requiere: `movies10` con `overview`; `client` y `MODEL` de la Parte 3.

In [ ]:
# --- Parte 4B (opcional): recomendador por género (SOLUCIÓN) ---
# Requiere: `ratings_movies` (Parte 1); `client` y `MODEL` (Parte 3).